---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${controller_service_account}
  namespace: ${namespace}
---
apiVersion: v1
kind: Service
metadata:
  name: garden-controller-manager
  namespace: ${namespace}
  labels:
    app: gardener
    role: controller-manager
spec:
  selector:
    app: gardener
    role: controller-manager
  ports:
  - port: ${controller_port}
    protocol: TCP
    targetPort: ${controller_port}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garden-controller-manager-configmap
  namespace: ${namespace}
data:
  config.yaml: |
    ---
    apiVersion: componentconfig.sapcloud.io/v1alpha1
    kind: ControllerManagerConfiguration
    clientConnection:
      acceptContentTypes: application/json
      contentType: application/json
      qps: 100
      burst: 130
    controller:
      healthCheckPeriod: 30s
      reconciliation:
        concurrentSyncs: 20
        resyncPeriod: 10m
        retryDuration: 1440m
    gardenNamespace: ${namespace}
    leaderElection:
      leaderElect: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      resourceLock: configmaps
    logLevel: info
    metrics:
      interval: 30s
    server:
      bindAddress: 0.0.0.0
      port: ${controller_port}
${domain_secret}
---
apiVersion: ${deployment_version}
kind: Deployment
metadata:
  name: garden-controller-manager
  namespace: ${namespace}
  labels:
    app: gardener
    role: controller-manager
spec:
  replicas: ${controller_replicas}
  selector:
    matchLabels:
      app: gardener
      role: controller-manager
  template:
    metadata:
      labels:
        app: gardener
        role: controller-manager
    spec:
      serviceAccountName: ${controller_service_account}
      containers:
      - name: garden-controller-manager
        image: ${controller_image}:${controller_version}
        imagePullPolicy: IfNotPresent
        command:
        - /garden-controller-manager
        - --config=/etc/garden-controller-manager/config.yaml
        livenessProbe:
          httpGet:
            path: /healthz
            port: ${controller_port}
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 750m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: garden-controller-manager-config
          mountPath: /etc/garden-controller-manager
      terminationGracePeriodSeconds: 3600
      volumes:
      - name: garden-controller-manager-config
        configMap:
          name: garden-controller-manager-configmap
