---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-domain
  namespace: ${namespace}
  labels:
    garden.sapcloud.io/role: internal-domain
  annotations:
    dns.garden.sapcloud.io/provider: aws-route53
    dns.garden.sapcloud.io/domain: ${domain}
    dns.garden.sapcloud.io/hostedZoneID: ${hosted_zone_id}
type: Opaque
data:
  accessKeyID:     ${route53_access_key_b64}
  secretAccessKey: ${route53_secret_key_b64}
